name: Python Package

on:
    push:
      branches: [ master ]
    workflow_dispatch:

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.8]

       steps:
        - uses: actions/checkout@v3

        - name: Initialize Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt     

        - name: Check docker installed or not
          run: docker run hello-world

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub access token

        - name: Push to docker hub
          uses: docker/build-push-action/@v4
          with:
            repository: ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKERHUB_REPO}}
            push: true
            tags: user/app:latest
